services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data:Z
    ports:
      - '${DB_PORT}:5432'
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  nginx:
    build:
      context: ./apps/kitchen-list-frontend
      dockerfile: Dockerfile
    image: ngnix
    ports:
      - '80:80'
    restart: always
    depends_on:
      - node
      - node2
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}

  node:
    build:
      context: ./apps/kitchen-list-backend
      dockerfile: Dockerfile
    image: node
    ports:
      - '3000:3000'
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - REDIS_SECRET=${REDIS_SECRET}
      - REDIS_URL=redis://redis:6379
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: wget --no-verbose --tries=10 --spider http://localhost:3000/api/healthcheck || exit 1
      timeout: 3s
      interval: 3s
      retries: 10
    depends_on:
      - redis
      - db
  node2:
    build:
       context: ./apps/kitchen-list-backend
       dockerfile: Dockerfile
    image: node2
    ports:
      - '3001:3000'
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - REDIS_SECRET=${REDIS_SECRET}
      - REDIS_URL=redis://redis:6379
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: wget --no-verbose --tries=10 --spider http://localhost:3000/api/healthcheck || exit 1
      timeout: 3s
      interval: 3s
      retries: 10
    depends_on:
      - redis
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  postgres-vol:
