services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      container_name: postgres
      volumes:
        - postgres-vol:/var/lib/postgresql/data:Z
      ports:
        - '${DB_PORT}:5432'
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]     
  nginx:
    image: ghcr.io/mmxzmax/kitchen-shopping-list-frontend:main
    ports:
      - '80:80'
    restart: always
    depends_on:
      - node
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}

  node:
    image: ghcr.io/mmxzmax/kitchen-shopping-list-backend:main
    ports:
      - '3000:3000'
    restart: always
    environment:
      - PORT=3000
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - REDIS_SECRET=${REDIS_SECRET}
      - REDIS_URL=${REDIS_URL}
      - DB_NAME=${DB_NAME}
      - TG_BOT_KEY=${TG_BOT_KEY}
    healthcheck:
      test: wget --no-verbose --tries=10 --spider http://localhost:3000/api/healthcheck || exit 1
      timeout: 3s
      interval: 3s
      retries: 10
    depends_on:
      - db  
      - redis
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db    
volumes:
  postgres-vol:                   