services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      container_name: postgres
      volumes:
        - postgres-vol:/var/lib/postgresql/data:Z
      ports:
        - '5432:5432'
  nginx:
    image: ghcr.io/mmxzmax/kitchen-shopping-list-frontend:main
    ports:
      - '80:80'
    restart: always
    depends_on:
      node:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}

  node:
    image: ghcr.io/mmxzmax/kitchen-shopping-list-backend:main
    ports:
      - '3000:3000'
    restart: always
    environment:
      - APP_PORT=3000
    healthcheck:
      test: wget --no-verbose --tries=10 --spider http://localhost:3000/api/healthcheck || exit 1
      timeout: 3s
      interval: 3s
      retries: 10
    depends_on:
      - db  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db    
volumes:
  postgres-vol:                   